create table if not exists public.urls (
  id bigint generated by default as identity primary key,
  original_url text not null,
  short_code text not null unique,
  click_count integer not null default 0,
  created_at timestamp with time zone not null default now()
);

create index if not exists urls_short_code_idx on public.urls (short_code);
